name: Package Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: "https://npm.pkg.github.com"

      - name: Configure NPM
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install Packages
        run: npm ci

      - name: Build Files
        run: npm run compile

      - name: Lint
        run: npm run eslint

      - name: Check Version Changes
        if: github.ref == 'refs/heads/main'
        uses: EndBug/version-check@v1
        id: check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Publish Package
        if: |
          steps.check.outputs.changed == 'true' &&
          github.ref == 'refs/heads/main'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
